network_path:
  value: rsc/jsh/ver3
  dtype: string

model_number:
  value: 20000
  dtype: string

p_gain:
  value: 100.0
  dtype: double

d_gain:
  value: 5.0
  dtype: double

plugin:
  raisin_iekf_plugin: # plugin package name
    rate:
      value: 500 # loop frequency
      dtype: double
